version: '3'

services:
  rf-mariadb:
    image: mariadb:latest
    container_name: rf-mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file: 
      - ./mariadb/.env
    networks:
      - rf-nextgen
    volumes:
      - ./mariadb/config:/etc/mysql/mariadb.conf.d
      - ./mariadb/mysql:/var/lib/mysql
    restart: always

  rf-rproxy:
    container_name: rf-rproxy
    image: nginx
    volumes:
      - ./nginx/rf_nextgen.conf:/etc/nginx/conf.d/rf_nextgen.conf
    ports:
      - 80:80
    networks:
      - rf-nextgen
    restart: always

  rfnextgen-app:
    image: mokshithshetty/rf_nextgen:${ENVIRONMENT}
    profiles: ["rfnextgen"]
    tty: true
    stdin_open: true
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rfnextgen-app
    ports:
      - "3001:3001" 
    networks:
      - rf-nextgen
    env_file:
      - ./.env
    expose:
      - "3001"
    restart: always
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    depends_on:
      - rf-mariadb
      - rf-rproxy    

networks:
  rf-nextgen:
    driver: bridge
